spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: root
  flyway:
    create-schemas: true
    schemas: user_manager_uni
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}