ALTER TABLE auction
    ADD COLUMN IF NOT EXISTS winner_id INTEGER;

ALTER TABLE auction
    ADD COLUMN IF NOT EXISTS winner_email VARCHAR(60);

ALTER TABLE auction
    ADD COLUMN IF NOT EXISTS owner_id INTEGER;
