name: Run tests

on:
  pull_request:
    branches: ["*"]

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Clean Gradle
        run: ./gradlew clean
      - name: Test all classes
        run: ./gradlew test